from .ops import *


OPMAP = {
    b'\x00': BRK,
    b'\x01': NOP,
    b'\x02': RET,
    b'\x03': BRA,
    b'\x04': BF,
    b'\x05': BT,
    b'\x06': JSR,
    b'\x07': CALL,
    b'\x08': PUSH,
    b'\x09': PUSHB,
    b'\x0a': PUSHW,
    b'\x0b': PUSHF,
    b'\x0c': PUSHA,
    b'\x0d': PUSHS,
    b'\x0e': PUSHSI,
    b'\x0f': PUSHSIB,
    b'\x10': PUSHSIW,
    b'\x11': PUSHI,
    b'\x12': PUSHII,
    b'\x13': PUSHIIB,
    b'\x14': PUSHIIW,
    b'\x15': PUSH0,
    b'\x16': PUSH1,
    b'\x17': PUSHM,
    b'\x18': POP,
    b'\x19': ADD,
    b'\x1a': SUB,
    b'\x1b': MUL,
    b'\x1c': DIV,
    b'\x1d': SHL,
    b'\x1e': SHR,
    b'\x1f': AND,
    b'\x20': OR,
    b'\x21': XOR,
    b'\x22': LAND,
    b'\x23': LOR,
    b'\x24': EQ,
    b'\x25': NE,
    b'\x26': LT,
    b'\x27': LE,
    b'\x28': GT,
    b'\x29': GE,
    b'\x2a': ASSIGN,
    b'\x2b': PLUS,
    b'\x2c': MINUS,
    b'\x2d': INV,
    b'\x2e': NOT,
    b'\x2f': BLK,
    b'\x30': ILLEGAL,
}